from datetime import datetime, timedelta, timezone

import bcrypt
import jwt

# 定义常量
SECRET_KEY = "02:45 AM, 8/29/2026, Lanzhou, Gansu, developing my blog with the assistance of DeepSeek Harness when I'm on duty during HW-2026, though, first thing first the codes are not generated by AI, I type them. Secondly, I want to go back home."
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30


# 将前端用户输入的密码加密为加盐hash值
def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


# 验证名为用户输入的明文密码加密为hash后是否与数据库中存储的hash相同，返回boolean值
def verify_password(plain_password: str, hashed_password: str) -> bool:
    return bcrypt.checkpw(plain_password.encode("utf-8"), hashed_password.encode("utf-8"))


# 签发：生成token，30分钟后蒸发：过期时间为当前时间+有效时间(ACCESS_TOKEN_EXPIRE_MINUTES，常量，定义为30分钟)
def create_access_token(data: dict) -> str:
    expire_time = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode = data.copy()
    to_encode["exp"] = expire_time
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


# 验签：验证token是否有效并取回
def decode_token(token: str) -> dict:
    return jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
